export interface ArticleContent {
  id: number;
  content: string;
}

export const ARTICLES_CONTENT_MOCK: ArticleContent[] = [
  {
    id: 1,
    content:
      "Monorepo to podejście, w którym wiele pakietów żyje w jednym repozytorium. Turborepo w połączeniu z pnpm workspaces daje nam potężne narzędzie do zarządzania zależnościami i cachowania buildów. Kluczem jest plik turbo.json definiujący pipeline — kolejność tasków, ich zależności i outputy do cache'owania. Dzięki temu rebuild dotyka tylko zmienionych pakietów. Konfiguracja pnpm-workspace.yaml wskazuje foldery apps/ i packages/, a każdy pakiet ma własny package.json z zależnościami workspace:*. TypeScript strict mode wymusza bezpieczeństwo typów w całym monorepo. Ważne jest też prawidłowe ustawienie tsconfig z references między pakietami, co przyspiesza typecheck. Turborepo potrafi równolegle uruchamiać taski, co drastycznie skraca czas CI/CD. W praktyce oznacza to, że zmiana w jednym pakiecie nie wymusza przebudowy całego repozytorium — Turborepo analizuje graf zależności i uruchamia tylko te taski, które są rzeczywiście dotknięte zmianą. Remote caching pozwala współdzielić wyniki buildów między członkami zespołu i środowiskami CI. Wystarczy skonfigurować token Vercel lub self-hosted cache server, a Turborepo automatycznie pobierze gotowe artefakty zamiast budować od zera. Dry run mode (turbo run build --dry) pozwala podejrzeć plan wykonania bez faktycznego uruchomienia. Filtrowanie tasków przez --filter=web... uruchamia build tylko dla wybranego pakietu i jego zależności. Warto też skonfigurować globalDependencies w turbo.json — pliki jak .env czy tsconfig.base.json, których zmiana powinna inwalidować cache wszystkich pakietów.",
  },
  {
    id: 2,
    content:
      "CSS Design System zaczyna się od tokenów — CSS custom properties definiujących kolory, typografię, spacing, promienie i cienie. Tokeny to single source of truth dla całego UI. Na nich budujemy semantic variables: --color-fg-primary, --color-bg-canvas, które zmieniają wartości w zależności od motywu. Ciemny motyw to podmiana tych zmiennych w selektorze [data-theme='dark']. System wspiera też prefers-color-scheme dla automatycznego wykrywania. Layout opiera się na tokenach spacing i CSS Grid. Reset normalizuje style przeglądarek, a typography.css ustawia skalę fontów. Całość importowana jest z pakietu @my-monorepo/styles, co zapewnia spójność między apps/ i packages/. Architektura tokenów dzieli się na trzy warstwy: primitive tokens (surowe wartości jak #1a1a2e), semantic tokens (mapujące na kontekst jak --color-bg-canvas) i component tokens (specyficzne dla komponentów jak --button-bg). Primitive tokens nigdy nie są używane bezpośrednio w komponentach — zawsze przez warstwę semantyczną. Dzięki temu zmiana motywu wymaga tylko podmianę mapowania semantic → primitive. System typografii definiuje skalę modularną — każdy rozmiar fontu jest mnożnikiem bazowego rozmiaru 1rem. Line-height i letter-spacing są sparowane z rozmiarem fontu w tokenach kompozytowych. Spacing tokens używają skali 4px — od --spacing-1 (4px) do --spacing-16 (64px). Border-radius tokens zapewniają spójne zaokrąglenia w całym UI. Shadow tokens definiują trzy poziomy elevation dla głębi wizualnej. Cały system jest dokumentowany w Storybook, gdzie każdy token ma wizualną reprezentację.",
  },
  {
    id: 3,
    content:
      "NestJS świetnie współpracuje z Prisma 7 dzięki driver adapter pattern. Zamiast pozwalać Prisma na bezpośrednie połączenie z bazą, tworzymy własny pg.Pool i przekazujemy go przez @prisma/adapter-pg. Daje to pełną kontrolę nad connection poolingiem. DatabaseService w NestJS inicjalizuje PrismaClient z adapterem w onModuleInit i zamyka połączenie w onModuleDestroy. Schema Prisma definiuje modele, relacje i indeksy. Migracje tworzymy przez prisma migrate dev, a na produkcji aplikujemy przez prisma migrate deploy. Prisma Client jest generowany do folderu generated/ i gitignorowany — każde środowisko generuje go lokalnie. Dzięki temu mamy pełną kontrolę nad połączeniami i możemy łatwo integrować dodatkowe funkcje PostgreSQL, jak listen/notify czy pg_stat_statements. Driver adapter pattern otwiera też drzwi do zaawansowanych scenariuszy — na przykład read replicas, gdzie zapytania SELECT trafiają do repliki, a mutacje do primary. Prisma 7 wspiera typed SQL queries przez prisma.$queryRawTyped, co daje bezpieczeństwo typów nawet dla surowych zapytań SQL. Middleware w Prisma pozwala dodać logowanie zapytań, mierzenie czasu wykonania czy soft-delete na poziomie ORM. W testach używamy prisma.$transaction z isolation level SERIALIZABLE, by zapewnić deterministyczne wyniki. Warto skonfigurować prisma.config.ts z custom output path, by generowany klient trafiał do dedykowanego folderu. Pool size konfigurujemy przez pg.Pool z min/max connections — dla małych VPS-ów sprawdza się max 5 połączeń z idle timeout 30 sekund.",
  },
  {
    id: 4,
    content:
      "Docker Compose pozwala definiować wielokontenerowe środowiska deklaratywnie. W naszym stacku dev mamy kontenery: web (Vite z hot-reload), backend (NestJS z watch mode), postgres, redis i nginx jako reverse proxy. Nginx routuje /api/* do backendu, a resztę do frontendu. Multi-stage builds w Dockerfile minimalizują rozmiar obrazów produkcyjnych — etap builder instaluje zależności i buduje, a etap runtime kopiuje tylko artefakty. Volumes montują kod źródłowy dla hot-reload w dev, ale w produkcji kod jest wbudowany w obraz. Docker networks izolują usługi, a healthchecki dbają o prawidłową kolejność startu. Kluczowe jest prawidłowe cache'owanie warstw Docker — najpierw kopiujemy package.json i pnpm-lock.yaml, instalujemy zależności, a dopiero potem kopiujemy kod źródłowy. Dzięki temu zmiana w kodzie nie wymaga ponownej instalacji node_modules. W dev używamy bind mounts dla kodu źródłowego, ale named volumes dla node_modules — to zapobiega nadpisaniu zależności przez lokalny folder. Compose profiles pozwalają uruchamiać różne zestawy usług — profil dev włącza hot-reload i debug, profil prod startuje zoptymalizowane obrazy. Environment variables definiujemy w .env files z interpolacją w docker-compose.yml. Healthchecki dla PostgreSQL używają pg_isready, dla Redis — redis-cli ping, a dla NestJS — curl na /api/health. Restart policy always zapewnia automatyczny restart po awarii, ale w dev używamy unless-stopped.",
  },
  {
    id: 5,
    content:
      "Vitest to natywny test runner dla Vite, współdzielący konfigurację i pipeline transformacji. W połączeniu z Testing Library testujemy komponenty React tak, jak używa ich użytkownik — przez role, labele i tekst, nie przez implementację. Setup file konfiguruje jsdom i rozszerza expect o matchers z @testing-library/jest-dom. Snapshot testy łapią niezamierzone zmiany w renderowanym HTML. Coverage zbieramy przez v8 provider z progami 80% dla lines, functions, branches i statements. W monorepo każdy pakiet ma własny vitest.config — web i components używają jsdom, backend używa Jest z ts-jest. Vitest watch mode wykorzystuje HMR Vite do natychmiastowego re-runu zmienionych testów — feedback loop jest znacznie szybszy niż w Jest. Testy komponentów renderujemy przez render() z Testing Library, a interakcje symulujemy przez userEvent — kliknięcia, wpisywanie tekstu, nawigacja klawiaturą. Asynchroniczne operacje testujemy przez waitFor i findBy queries, które automatycznie czekają na pojawienie się elementów. Mock Service Worker (MSW) przechwytuje requesty HTTP na poziomie service workera, co pozwala testować komponenty z realistycznymi odpowiedziami API bez uruchamiania backendu. Vitest wspiera concurrent mode — testy w jednym pliku mogą biec równolegle dzięki test.concurrent. In-source testing pozwala pisać testy bezpośrednio w pliku źródłowym — Vitest automatycznie je wyodrębnia i uruchamia. CI pipeline uruchamia vitest run z --reporter=junit dla integracji z GitHub Actions.",
  },
  {
    id: 6,
    content:
      'ES Modules w Node.js wymagają kilku kluczowych zmian. Package.json musi mieć "type": "module". Importy relatywne wymagają rozszerzenia .js — nawet dla plików .ts, bo TypeScript kompiluje do .js. Dynamic import() zastępuje require(). __dirname i __filename nie istnieją — używamy import.meta.url z fileURLToPath. Tsconfig potrzebuje "module": "nodenext" i "moduleResolution": "nodenext". Niektóre pakiety npm nadal są CJS — Node.js potrafi je importować przez named imports, ale default export wymaga .default. ESM jest przyszłością Node.js i daje korzyści jak tree-shaking i statyczna analiza importów. Migracja z CJS do ESM w istniejącym projekcie wymaga systematycznego podejścia. Zaczynamy od zmiany "type": "module" w package.json, co sprawia że wszystkie pliki .js są traktowane jako ESM. Pliki CJS muszą dostać rozszerzenie .cjs. Top-level await działa natywnie w ESM — nie potrzeba async wrapper function. JSON imports wymagają assert { type: "json" } lub nowego import attributes syntax z with { type: "json" }. Glob patterns w importach nie są wspierane natywnie — używamy fs.readdir z filter lub biblioteki jak glob. Conditional exports w package.json przez pole "exports" pozwalają definiować różne entry points dla ESM i CJS konsumentów pakietu. Import maps w Node.js pozwalają aliasować pakiety bez bundlera. Debugowanie ESM w VS Code wymaga konfiguracji launch.json z "type": "node" i odpowiednim runtimeArgs.',
  },
  {
    id: 7,
    content:
      "GitHub Actions to silnik CI/CD zintegrowany z GitHubem. Workflow definiujemy w YAML w .github/workflows/. Nasz pipeline: checkout → setup Node + pnpm → install → typecheck → build → test → push do GHCR → deploy na VPS. Cache'ujemy node_modules przez actions/cache z kluczem opartym na pnpm-lock.yaml. Matrix strategy pozwala testować na wielu wersjach Node. Secrets przechowują tokeny i klucze SSH. Deployment na Mikrus VPS przez SSH — pull nowych obrazów z GHCR i docker compose up. Branch protection rules wymuszają przejście CI przed merge do main. Reusable workflows pozwalają współdzielić logikę CI między repozytoriami — definiujemy workflow_call z inputs i secrets. Composite actions grupują powtarzalne kroki w jedną akcję z własnym action.yml. Concurrency groups zapobiegają równoległym deploymentom na to samo środowisko — nowy run anuluje poprzedni. Artifact upload/download pozwala przekazywać build outputy między jobami — np. job build tworzy artefakty, a job deploy je pobiera i deployuje. Environment protection rules wymagają manualnego approval przed deploymentem na produkcję. OIDC token authentication eliminuje potrzebę przechowywania długoterminowych credentials — Actions dostaje krótkotrwały token od cloud providera. Self-hosted runners na VPS dają pełną kontrolę nad środowiskiem CI — przydatne gdy potrzebujemy dostępu do prywatnej sieci lub specyficznego hardware.",
  },
  {
    id: 8,
    content:
      "Nginx jako reverse proxy to standard w produkcyjnych deploymentach. Konfiguracja upstream definiuje backendy z load balancingiem. Location /api/ przekierowuje do NestJS z proxy_pass i stripuje prefix. TLS termination z certyfikatem Cloudflare Origin — ssl_certificate i ssl_certificate_key. Security headers: X-Content-Type-Options, X-Frame-Options, Strict-Transport-Security. Gzip compression dla text/html, application/json i CSS. Cache headers dla statycznych assetów — immutable z długim max-age dla hashowanych plików Vite. Worker processes ustawiamy na auto, a worker connections na 1024 dla małych VPS-ów. Konfiguracja proxy_pass wymaga uwagi na trailing slash — location /api/ z proxy_pass http://backend/ stripuje /api prefix, bez slasha zachowuje pełną ścieżkę. proxy_set_header X-Real-IP i X-Forwarded-For przekazują prawdziwy IP klienta do backendu. proxy_set_header Host $host zapewnia prawidłowe rozwiązywanie nazw w backendzie. WebSocket upgrade wymaga dodatkowych proxy_set_header Upgrade i Connection. Buffer settings kontrolują jak Nginx buforuje odpowiedzi — proxy_buffering off dla SSE i streaming. Rate limiting przez limit_req_zone chroni przed DDoS — konfigurujemy strefę z rate 10r/s i burst 20. Access log w formacie JSON ułatwia parsowanie przez narzędzia monitoringu. Error pages konfigurujemy przez error_page 502 /502.html z lokalizacją statycznych fallbacków. Try_files $uri $uri/ /index.html obsługuje client-side routing w SPA.",
  },
  {
    id: 9,
    content:
      "PostgreSQL 17 wprowadza incremental backup — pg_basebackup z --incremental pozwala tworzyć przyrostowe kopie. JSON_TABLE upraszcza parsowanie JSON w zapytaniach SQL. Nowy merge command jest w pełni zgodny ze standardem SQL. Performance: partition pruning jest szybszy, a vacuum ma lepszą obsługę dużych tabel. Monitoring przez pg_stat_io daje wgląd w I/O operacje. Dla aplikacji webowych kluczowe jest connection pooling — PgBouncer lub wbudowany w Prisma. Indeksy GIN dla full-text search i JSONB, B-tree dla prostych zapytań. EXPLAIN ANALYZE to podstawowe narzędzie do optymalizacji. Partycjonowanie tabel przez PARTITION BY RANGE na kolumnie daty pozwala efektywnie zarządzać dużymi zbiorami danych — stare partycje można archiwizować lub usuwać bez wpływu na bieżące dane. Materialized views z REFRESH CONCURRENTLY przyspieszają złożone zapytania analityczne bez blokowania odczytów. Row Level Security (RLS) implementuje autoryzację na poziomie wiersza — polityki definiują kto widzi jakie dane, a PostgreSQL egzekwuje je transparentnie. pg_trgm extension wspiera fuzzy search i similarity matching — przydatne do wyszukiwania z tolerancją literówek. LISTEN/NOTIFY implementuje pub/sub bezpośrednio w bazie — idealny mechanizm do powiadamiania aplikacji o zmianach w danych. Logical replication pozwala selektywnie replikować wybrane tabele do innych instancji PostgreSQL, co przydaje się przy migracji i analityce.",
  },
  {
    id: 10,
    content:
      "Redis 7 to nie tylko cache — to wielofunkcyjny data store. W naszym stacku służy jako cache odpowiedzi API i session store. AOF (Append Only File) persistence zapewnia trwałość danych po restarcie. Konfiguracja eviction policy: allkeys-lru usuwa najrzadziej używane klucze gdy pamięć się kończy. TTL na kluczach automatycznie czyści stare dane. W NestJS integrujemy przez ioredis — RedisService zarządza połączeniem i udostępnia metody get/set/del. Cache-aside pattern: sprawdź Redis → jeśli brak, pobierz z DB → zapisz w Redis. Pub/Sub w Redis nadaje się do real-time notyfikacji między instancjami. Redis Functions zastępują Lua scripting — pozwalają pisać złożoną logikę po stronie serwera w JavaScript. Streams to struktura danych do event sourcingu — idealny do logowania zdarzeń i kolejkowania zadań z consumer groups. Redis Search module dodaje pełnotekstowe wyszukiwanie i secondary indexing bez dodatkowej infrastruktury. JSON module pozwala przechowywać i queryować dokumenty JSON natywnie, z JSONPath queries i atomic updates na zagnieżdżonych polach. Pipeline mode grupuje wiele komend w jednym round-trip do serwera — drastycznie redukuje latencję przy batch operacjach. Redis Sentinel zapewnia high availability z automatycznym failoverem — monitoruje mastera i promuje replikę w razie awarii. Cluster mode partycjonuje dane między wieloma nodami z automatycznym reshardingiem.",
  },
  {
    id: 11,
    content:
      "Dostępność (a11y) to nie tylko wymóg prawny, ale dobra praktyka UX. W React zaczynamy od semantycznego HTML — button zamiast div z onClick, nav dla nawigacji, main dla głównej treści. ARIA attributes uzupełniają semantykę: aria-label, aria-expanded, aria-live dla dynamicznych treści. Focus management — po otwarciu modala focus idzie na pierwszy interaktywny element, po zamknięciu wraca. Skip links pozwalają pominąć nawigację. Kontrast minimum 4.5:1 dla tekstu. Testing Library naturalnie wspiera a11y — getByRole wymusza prawidłowe role. Axe-core w testach automatycznie wykrywa problemy. Keyboard navigation to fundament dostępności — każdy interaktywny element musi być osiągalny tabulacją, a custom widgety potrzebują obsługi Enter, Space, Escape i strzałek zgodnie ze wzorcami WAI-ARIA. Focus trap w modalach zapewnia, że Tab nie wyjdzie poza dialog — implementujemy go przez nasłuchiwanie keydown i przekierowanie focusu. aria-live regions powiadamiają screen readery o dynamicznych zmianach — polite czeka na przerwę w czytaniu, assertive przerywa natychmiast. Reduced motion — prefers-reduced-motion media query wyłącza animacje dla użytkowników z vestibular disorders. Screen reader testing wymaga ręcznego sprawdzenia z NVDA (Windows), VoiceOver (macOS) lub Orca (Linux). Landmark roles (main, nav, banner, contentinfo) pomagają screen readerom w nawigacji po stronie. Alt text na obrazach powinien opisywać treść, nie wygląd — dekoracyjne obrazy dostają alt pustego stringa.",
  },
  {
    id: 12,
    content:
      "Vite 7 wprowadza Environment API — zunifikowany sposób na konfigurację różnych środowisk (client, SSR, workery). Nowy dev server jest szybszy dzięki natywnym ESM i optymalizacjom HMR. Dependency pre-bundling przez esbuild jest teraz bardziej inteligentny — automatycznie wykrywa zmiany w node_modules. CSS Modules mają lepszą obsługę z typowanymi importami. Config file wspiera TypeScript bez dodatkowej konfiguracji. Build przez Rollup 4 generuje mniejsze bundle dzięki lepszemu tree-shaking. Plugin API jest stabilniejsze z pełną kompatybilnością wsteczną. Migracja z Vite 6 wymaga minimalnych zmian — głównie aktualizacji zależności. Environment API pozwala definiować odrębne konfiguracje resolve, plugins i optymalizacje dla każdego środowiska — np. client nie potrzebuje polyfilli Node.js, a SSR nie potrzebuje code splitting. HMR w Vite 7 propaguje zmiany z chirurgiczną precyzją — edycja CSS Module odświeża tylko ten komponent, bez reload całej strony. Vite wspiera glob imports przez import.meta.glob — lazy loading modułów pasujących do wzorca, z eager opcją do static imports. Library mode pozwala budować pakiety npm — konfiguracja build.lib definiuje entry points, formats (ESM, CJS) i external dependencies. Preview command (vite preview) serwuje build output lokalnie, symulując produkcyjny deployment. Rollup plugin compatibility oznacza, że większość pluginów Rollup działa w Vite bez zmian. Optimized deps discovery automatycznie pre-bundluje nowe zależności wykryte podczas dev — bez ręcznego restartu.",
  },
  {
    id: 13,
    content:
      "CSS Modules oferują scoped styles bez runtime overhead — klasy są hashowane w build time. Każdy komponent importuje swój .module.css i używa klas jako obiekt JS. Zero kolizji nazw, zero bundle overhead. Styled-components dają dynamic styling z JS, ale kosztem runtime: generowanie CSS w JS, większy bundle, hydration issues w SSR. Performance: CSS Modules wygrywają — style są statyczne, parsowane raz przez przeglądarkę. DX: styled-components mają lepszą ergonomię dla dynamicznych stylów. W naszym projekcie wybieramy CSS Modules + postcss-nesting dla nested selectors. Design tokens przez CSS custom properties działają z oboma podejściami. Composition w CSS Modules działa przez composes — pozwala dziedziczyć klasy z innych modułów bez duplikacji CSS. Global styles definiujemy przez :global() wrapper w module file, co przydaje się do nadpisywania styli bibliotek zewnętrznych. postcss-nesting pozwala na składnię nested selectors zgodną ze specyfikacją CSS Nesting — & selector odnosi się do rodzica, co czyni kod czytelniejszym. Dynamiczne warianty w CSS Modules implementujemy przez conditional className joining — np. styles[variant] lub template literals. CSS Layers (@layer) organizują specyficzność — warstwa reset < base < components < utilities zapobiega wojnom specyficzności. Container queries (@container) pozwalają na responsive design na poziomie komponentu zamiast viewportu — idealne dla reusable components w różnych kontekstach layout. Vite automatycznie generuje typowania dla CSS Modules gdy włączymy css.modules.localsConvention w konfiguracji.",
  },
  {
    id: 14,
    content:
      "Prisma Migrate to deklaratywny system migracji. Definiujesz docelowy schemat w schema.prisma, a Prisma generuje SQL migracji. prisma migrate dev tworzy migrację, aplikuje ją i regeneruje klienta. prisma migrate deploy aplikuje oczekujące migracje na produkcji — bez generowania nowych. prisma migrate reset czyści bazę i aplikuje wszystkie od zera — przydatne w dev. Seeding przez prisma db seed wykonuje skrypt TypeScript wypełniający bazę danymi testowymi. Best practice: każda migracja w osobnym folderze z timestamp, SQL i metadata. Nigdy nie edytuj istniejących migracji — twórz nowe korygujące. Shadow database to mechanizm, który Prisma używa w dev do porównania aktualnego schematu z docelowym — tworzy tymczasową bazę, aplikuje wszystkie migracje i generuje diff. W CI/CD pipeline sprawdzamy stan migracji przez prisma migrate status, który wykrywa drift między schematem a bazą. Custom migration SQL dodajemy ręcznie w wygenerowanym pliku migration.sql — przydatne do data migration, tworzenia funkcji SQL czy triggerów. Prisma Pulse to real-time extension — nasłuchuje zmian w bazie i streamuje je do aplikacji przez type-safe API. Prisma Accelerate dodaje global edge cache i connection pooling — przydatne dla serverless deploymentów gdzie cold start connection do bazy jest kosztowny. Schema validation przez prisma validate sprawdza poprawność schematu bez generowania migracji.",
  },
  {
    id: 15,
    content:
      "React 19 to największa zmiana od Hooks. use() hook pozwala czytać Promise i Context w render — zastępuje useEffect dla data fetching. Server Components renderują się na serwerze, redukując bundle klienta. Actions to nowy wzorzec dla mutacji — useActionState zarządza stanem formularza, useOptimistic daje natychmiastowy feedback. ref jest teraz zwykłym propem — koniec z forwardRef. Suspense boundaries obsługują loading states deklaratywnie. Compiler React (dawniej React Forget) automatycznie memoizuje komponenty. Migracja z React 18: usuń niepotrzebne useMemo/useCallback, zamień useEffect na use() dla fetching. use() hook ma fundamentalną różnicę od innych hooków — można go wywoływać warunkowo, wewnątrz pętli czy bloku if. Rzucony Promise wstrzymuje renderowanie komponentu i aktywuje najbliższy Suspense boundary. Server Actions definiujemy przez dyrektywę 'use server' — funkcje mogą być przekazywane jako prop action w formularzu, a React automatycznie serializuje dane formularza i wywołuje server function. useFormStatus udostępnia stan bieżącej akcji formularza — pending, data, method — przydatny do wyłączania przycisku submit podczas przetwarzania. Transitions przez useTransition oznaczają aktualizacje jako low-priority — UI pozostaje responsywny podczas przetwarzania. Document metadata — tytuł i meta tagi mogą być renderowane bezpośrednio w komponentach przez tagi title i meta, a React automatycznie hoistuje je do head. Strict Mode w React 19 symuluje podwójne renderowanie tylko w development, pomagając wykryć side effecty w render phase.",
  },
];
