import type { FilterNode } from "@features/SideTreeNavigation/types/menu.types";

export const blogFilterTree: FilterNode[] = [
  {
    id: "categories",
    label: "Kategorie",
    children: [
      {
        id: "frontend",
        label: "Frontend",
        children: [
          { id: "react", label: "React" },
          { id: "vue", label: "Vue" },
          { id: "angular", label: "Angular" },
          { id: "svelte", label: "Svelte" },
          { id: "css", label: "CSS" },
          { id: "nextjs", label: "Next.js" },
          { id: "nuxt", label: "Nuxt" },
          { id: "remix", label: "Remix" },
          { id: "astro", label: "Astro" },
          { id: "solidjs", label: "SolidJS" },
          { id: "preact", label: "Preact" },
          { id: "qwik", label: "Qwik" },
          { id: "htmx", label: "HTMX" },
          { id: "alpine", label: "Alpine.js" },
          { id: "lit", label: "Lit" },
          { id: "stencil", label: "Stencil" },
          { id: "ember", label: "Ember.js" },
          { id: "backbone", label: "Backbone.js" },
          { id: "mithril", label: "Mithril" },
          { id: "inferno", label: "Inferno" },
          { id: "riot", label: "Riot.js" },
          { id: "marko", label: "Marko" },
          { id: "stimulus", label: "Stimulus" },
          { id: "petite-vue", label: "Petite Vue" },
          { id: "hyperapp", label: "Hyperapp" },
          { id: "typescript", label: "TypeScript" },
          { id: "javascript", label: "JavaScript" },
          { id: "html5", label: "HTML5" },
          { id: "sass", label: "Sass" },
          { id: "less", label: "Less" },
          { id: "tailwind", label: "Tailwind CSS" },
          { id: "bootstrap", label: "Bootstrap" },
          { id: "bulma", label: "Bulma" },
          { id: "foundation", label: "Foundation" },
          { id: "materialize", label: "Materialize" },
          { id: "chakra-ui", label: "Chakra UI" },
          { id: "mui", label: "Material UI" },
          { id: "ant-design", label: "Ant Design" },
          { id: "radix", label: "Radix UI" },
          { id: "headless-ui", label: "Headless UI" },
          { id: "shadcn", label: "shadcn/ui" },
          { id: "daisyui", label: "DaisyUI" },
          { id: "mantine", label: "Mantine" },
          { id: "park-ui", label: "Park UI" },
          { id: "panda-css", label: "Panda CSS" },
          { id: "vanilla-extract", label: "Vanilla Extract" },
          { id: "styled-components", label: "Styled Components" },
          { id: "emotion", label: "Emotion" },
          { id: "css-modules", label: "CSS Modules" },
          { id: "postcss", label: "PostCSS" },
          { id: "webpack", label: "Webpack" },
          { id: "vite", label: "Vite" },
          { id: "esbuild", label: "esbuild" },
          { id: "rollup", label: "Rollup" },
          { id: "parcel", label: "Parcel" },
          { id: "turbopack", label: "Turbopack" },
          { id: "rspack", label: "Rspack" },
          { id: "swc", label: "SWC" },
          { id: "babel", label: "Babel" },
          { id: "biome", label: "Biome" },
          { id: "eslint", label: "ESLint" },
          { id: "prettier", label: "Prettier" },
          { id: "stylelint", label: "Stylelint" },
          { id: "storybook", label: "Storybook" },
          { id: "chromatic", label: "Chromatic" },
          { id: "vitest", label: "Vitest" },
          { id: "jest", label: "Jest" },
          { id: "cypress", label: "Cypress" },
          { id: "playwright", label: "Playwright" },
          { id: "testing-library", label: "Testing Library" },
          { id: "msw", label: "MSW" },
          { id: "react-query", label: "React Query" },
          { id: "swr", label: "SWR" },
          { id: "zustand", label: "Zustand" },
          { id: "jotai", label: "Jotai" },
          { id: "recoil", label: "Recoil" },
          { id: "redux", label: "Redux" },
          { id: "mobx", label: "MobX" },
          { id: "xstate", label: "XState" },
          { id: "pinia", label: "Pinia" },
          { id: "vuex", label: "Vuex" },
          { id: "ngrx", label: "NgRx" },
          { id: "react-router", label: "React Router" },
          { id: "tanstack-router", label: "TanStack Router" },
          { id: "react-hook-form", label: "React Hook Form" },
          { id: "formik", label: "Formik" },
          { id: "zod", label: "Zod" },
          { id: "yup", label: "Yup" },
          { id: "framer-motion", label: "Framer Motion" },
          { id: "gsap", label: "GSAP" },
          { id: "three-js", label: "Three.js" },
          { id: "d3", label: "D3.js" },
          { id: "chart-js", label: "Chart.js" },
          { id: "recharts", label: "Recharts" },
          { id: "i18next", label: "i18next" },
          { id: "date-fns", label: "date-fns" },
          { id: "lodash", label: "Lodash" },
          { id: "axios", label: "Axios" },
          { id: "pwa", label: "PWA" },
          { id: "web-components", label: "Web Components" },
          { id: "wasm", label: "WebAssembly" },
        ],
      },
      {
        id: "backend",
        label: "Backend",
        children: [
          { id: "node", label: "Node.js" },
          { id: "python", label: "Python" },
        ],
      },
    ],
  },
  {
    id: "tags",
    label: "Tagi",
    children: [
      { id: "new", label: "Nowości" },
      { id: "sale", label: "Wyprzedaż" },
    ],
  },
  {
    id: "authors",
    label: "Autorzy",
    children: [
      { id: "adam", label: "Adam Zagórski" },
      { id: "jan", label: "Jan Kowalski" },
    ],
  },
  {
    id: "dates",
    label: "Daty publikacji",
    children: [
      { id: "sty-2026", label: "Styczeń 2026" },
      { id: "lut-2026", label: "Luty 2026" },
      { id: "mar-2026", label: "Marzec 2026" },
    ],
  },
  {
    id: "types",
    label: "Typy wpisów",
    children: [
      { id: "sponsored", label: "Sponsorowane" },
      { id: "non-sponsored", label: "Nie sponsorowane" },
    ],
  },
];
