# Optional dev override: expose DB/cache ports to the host.
# Usage:
#   docker compose -f infrastructure/compose/dev.yml -f infrastructure/compose/dev.expose.yml up -d

services:
  postgres:
    networks:
      - private
      - public
    ports:
      - "5432:5432"

  redis:
    networks:
      - private
      - public
    ports:
      - "6379:6379"
