# Server-only production compose.
#
# This file is meant to live on the server under $APP_DIR and pull images from GHCR.
# It intentionally does NOT contain any `build:` sections, so the server never needs
# a full repo checkout and cannot accidentally build dev images.

services:
  migrate:
    image: ghcr.io/adamzagorski92/turbo-adam-migrate:${IMAGE_TAG:-latest}
    container_name: my-migrate
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - private
    restart: "no"

  nginx:
    image: ghcr.io/adamzagorski92/turbo-adam-nginx:${IMAGE_TAG:-latest}
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../certs:/etc/nginx/certs:ro
    depends_on:
      - web
      - backend
    networks:
      - public
    restart: unless-stopped

  backend:
    image: ghcr.io/adamzagorski92/turbo-adam-backend:${IMAGE_TAG:-latest}
    container_name: my-backend
    environment:
      NODE_ENV: production
      PORT: "3000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - redis
      - postgres
    networks:
      - public
      - private
    restart: unless-stopped

  web:
    image: ghcr.io/adamzagorski92/turbo-adam-web:${IMAGE_TAG:-latest}
    container_name: my-web
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - public
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: my-redis
    volumes:
      - redis_data:/data
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - private
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - private
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true
