# Local production-like compose.
#
# Differences vs production.server.yml:
# - builds images from the local repo (no GHCR pull required)
# - HTTP only (no TLS/origin certs)
# - publishes nginx on ${APP_HTTP_PORT:-8080}

services:
  migrate:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
      target: migrate
    container_name: my-migrate
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - private
    restart: "no"

  nginx:
    build:
      context: ../..
      dockerfile: infrastructure/nginx/Dockerfile.local
    container_name: my-nginx
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
    depends_on:
      - web
      - backend
    networks:
      - public
    restart: unless-stopped

  backend:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
      target: runtime
    container_name: my-backend
    environment:
      NODE_ENV: production
      PORT: "3000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - redis
      - postgres
    networks:
      - public
      - private
    restart: unless-stopped

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: my-web
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - public
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: my-redis
    volumes:
      - redis_data:/data
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - private
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - private
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true
